In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets-py/crime.csv
/kaggle/input/datasets-py/Project5_Housing_Data.csv
/kaggle/input/datasets-py/Project8_Netflix_Dataset.csv
/kaggle/input/datasets-py/Project2-CarsDataset.csv
/kaggle/input/datasets-py/Project_Weather_Dataset.csv
/kaggle/input/datasets-py/Covid_19_data.csv
/kaggle/input/datasets-py/Project6_Census_2011.csv
/kaggle/input/datasets-py/Project7_Udemy_Dataset.csv

In [23]:
df = pd.read_csv('/kaggle/input/datasets-py/Project8_Netflix_Dataset.csv')
df.head()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
df.shape

(7789, 11)

In [5]:
df.duplicated().sum()

2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Id       7789 non-null   object
 1   Category      7789 non-null   object
 2   Title         7789 non-null   object
 3   Director      5401 non-null   object
 4   Cast          7071 non-null   object
 5   Country       7282 non-null   object
 6   Release_Date  7779 non-null   object
 7   Rating        7782 non-null   object
 8   Duration      7789 non-null   object
 9   Type          7789 non-null   object
 10  Description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB

In [24]:
df[df.duplicated(keep = False)]

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
683,s684,Movie,Backfire,Dave Patten,"Black Deniro, Byron ""Squally"" Vinson, Dominic ...",United States,"April 5, 2019",TV-MA,97 min,"Dramas, Independent Movies, Thrillers",When two would-be robbers accidentally kill a ...
4839,s6621,Movie,The Lost Okoroshi,Abba T. Makama,"Seun Ajayi, Judith Audu, Tope Tedela, Ifu Enna...",Nigeria,"September 4, 2020",TV-MA,94 min,"Comedies, Dramas, Independent Movies",A disillusioned security guard transforms into...
6300,s684,Movie,Backfire,Dave Patten,"Black Deniro, Byron ""Squally"" Vinson, Dominic ...",United States,"April 5, 2019",TV-MA,97 min,"Dramas, Independent Movies, Thrillers",When two would-be robbers accidentally kill a ...
6622,s6621,Movie,The Lost Okoroshi,Abba T. Makama,"Seun Ajayi, Judith Audu, Tope Tedela, Ifu Enna...",Nigeria,"September 4, 2020",TV-MA,94 min,"Comedies, Dramas, Independent Movies",A disillusioned security guard transforms into...

In [25]:
# removing duplicates from the data frame and keeping only first occurence
df = df.drop_duplicates(keep="first")

In [27]:
df[df.Show_Id == 's684']

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
683,s684,Movie,Backfire,Dave Patten,"Black Deniro, Byron ""Squally"" Vinson, Dominic ...",United States,"April 5, 2019",TV-MA,97 min,"Dramas, Independent Movies, Thrillers",When two would-be robbers accidentally kill a ...

In [28]:
df.isnull().sum()

Show_Id            0
Category           0
Title              0
Director        2388
Cast             718
Country          507
Release_Date      10
Rating             7
Duration           0
Type               0
Description        0
dtype: int64

In [46]:
# For 'House of Cards', what is the Show Id and Who is the Director of this show ?
df[df.Title.str.contains('House of Cards') == True][['Show_Id','Director']]

     Show_Id                                           Director
2832   s2833  Robin Wright, David Fincher, Gerald McRaney, J...

In [51]:
df['New_Data'] = pd.to_datetime(df['Release_Date'], format="mixed")
df.dtypes

Show_Id                 object
Category                object
Title                   object
Director                object
Cast                    object
Country                 object
Release_Date            object
Rating                  object
Duration                object
Type                    object
Description             object
New_Data        datetime64[ns]
dtype: object

In [53]:
# display the no.of flims added to netflix by year wise
df["New_Data"].dt.year.value_counts()

New_Data
2019.0    2153
2020.0    2009
2018.0    1685
2017.0    1225
2016.0     443
2021.0     117
2015.0      88
2014.0      25
2011.0      13
2013.0      11
2012.0       3
2008.0       2
2009.0       2
2010.0       1
Name: count, dtype: int64

In [62]:
# group by tv shows and movies
df.groupby('Category').Category.count()

Category
Movie      5377
TV Show    2410
Name: Category, dtype: int64

In [76]:
df.fillna('NaN')

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,New_Data
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
7784,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19
7785,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02
7786,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25
7787,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31
7788,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01

In [78]:
df['Cast'] = df['Cast'].fillna('')

In [81]:
df[df.Cast.str.contains('Vijay')]

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,New_Data
251,s252,Movie,A Wednesday,Neeraj Pandey,"Anupam Kher, Naseeruddin Shah, Jimmy Shergill,...",India,"November 1, 2018",TV-MA,103 min,"Action & Adventure, Dramas, International Movies","After receiving an anonymous tip about a bomb,...",2018-11-01
264,s265,Movie,Aadu 2,Midhun Manuel Thomas,"Jayasurya, Vinayakan, Sunny Wayne, Vijay Babu,...",India,"May 15, 2018",TV-MA,150 min,"Comedies, International Movies",When Shaji Pappan and his gang of goofy outlaw...,2018-05-15
501,s502,Movie,Anarkali of Aarah,Avinash Das,"Swara Bhaskar, Sanjay Mishra, Vijay Kumar, Pan...",India,"August 1, 2017",TV-MA,111 min,"Dramas, Independent Movies, International Movies",After being sexually harassed by a drunken pol...,2017-08-01
555,s556,Movie,Anwar,Manish Jha,"Siddharth Koirala, Nauheed Cyrusi, Manisha Koi...",India,"December 31, 2019",TV-14,134 min,"Dramas, Independent Movies, International Movies",Seeking refuge in a Hindu temple after the tra...,2019-12-31
581,s582,Movie,Arjun: The Warrior Prince,Arnab Chaudhuri,"Yudhveer Bakoliya, Ashok Banthia, Ravi Khanwil...",India,"November 1, 2018",TV-14,91 min,"Action & Adventure, Dramas, International Movies",This animated retelling of the classic Indian ...,2018-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...
7393,s7392,Movie,Vanjagar Ulagam,Manoj Beedha,"Guru Somasundaram, Cibi Bhuvana Chandran, Vish...",India,"December 15, 2018",TV-MA,145 min,"Dramas, International Movies, Thrillers",Shyam wakes to discover he's suspected in a mu...,2018-12-15
7667,s7666,Movie,World Famous Lover,Kranthi Madhav,"Vijay Deverakonda, Raashi Khanna, Aishwarya Ra...",India,"April 15, 2020",TV-MA,147 min,"Dramas, International Movies, Romantic Movies",When his frustrated girlfriend decides to leav...,2020-04-15
7693,s7692,Movie,Y.M.I.: Yeh Mera India,N. Chandra,"Anupam Kher, Atul Kulkarni, Aakash Pandey, Mil...",India,"March 1, 2018",TV-MA,137 min,"Dramas, Independent Movies, International Movies","The lives of a middle-aged soap opera addict, ...",2018-03-01
7703,s7702,Movie,Yeh Ballet,Sooni Taraporevala,"Julian Sands, Manish Chauhan, Achintya Bose, J...",India,"February 21, 2020",TV-MA,117 min,"Dramas, International Movies","Discovered by an eccentric ballet master, two ...",2020-02-21
7756,s7755,Movie,Yuva,Mani Ratnam,"Ajay Devgn, Abhishek Bachchan, Vivek Oberoi, E...",India,"March 1, 2018",TV-14,160 min,"Dramas, International Movies",An accident on a bridge ties together three yo...,2018-03-01

In [91]:
# show unique india directors
india_directors = pd.DataFrame(df[df['Country'] == 'India'].Director.unique())

In [93]:
india_directors.head(100)

                     0
0        Shravan Kumar
1         Vikram Bhatt
2   Swapnaneel Jayakar
3                 Onir
4         Vijay Milton
..                 ...
95    Mahesh Manjrekar
96          Smeep Kang
97       Sneha Taurani
98        Nishil Sheth
99      Venky Kudumula

[100 rows x 1 columns]